// Generated from backend/docs/swagger.json by scripts/generate-api-types.mjs.
// Do not edit this file directly. Run `npm run api:types` instead.

export type ApiErrorResponse = {
	error: string;
};

export type ArtistIDRequest = {
	artist_id: number;
};

export type AuthRequest = {
	email: string;
	password: string;
};

export type CreateAlbumRequest = {
	artist_id: number;
	spotify_id?: string;
	title: string;
};

export type CreateArtistRequest = {
	cover_url?: string;
	name: string;
	spotify_id?: string;
};

export type MessageResponse = {
	message: string;
};

export type RefreshTokenRequest = {
	refresh_token: string;
};

export type SpotifyAlbumArtist = {
	id: string;
	name: string;
};

export type SpotifyAlbumSearchResult = {
	artists: SpotifyAlbumArtist[];
	id: string;
	images: SpotifyImage[];
	name: string;
	release_date: string;
};

export type SpotifyArtistSearchResult = {
	id: string;
	images: SpotifyImage[];
	name: string;
};

export type SpotifyImage = {
	height: number;
	url: string;
	width: number;
};

export type TokenResponse = {
	access_token: string;
	expires_in: number;
	refresh_token: string;
	token_type: string;
};

export type UpdateAlbumRequest = {
	artist_id: number;
	comment?: string;
	cover_url?: string;
	listened?: boolean;
	listened_at?: string;
	rating?: number;
	spotify_id?: string;
	title?: string;
	year?: number;
};

export type UpdateArtistRequest = {
	cover_url?: string;
	name?: string;
	spotify_id?: string;
};

export type Album = {
	artist_id: number;
	comment?: string;
	cover_url?: string;
	created_at: string;
	id: number;
	listened: boolean;
	listened_at?: string;
	rating?: number;
	spotify_id?: string;
	title: string;
	year?: number;
};

export type Artist = {
	cover_url?: string;
	created_at: string;
	id: number;
	name: string;
	spotify_id?: string;
};
